"""Create user messages model

Revision ID: 8413cd9caa8d
Revises: d6effd9127ea
Create Date: 2022-03-02 14:42:55.529372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8413cd9caa8d'
down_revision = 'd6effd9127ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_messages', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_messages', type_='unique')
    # ### end Alembic commands ###
